{% set name = "fastdownload" %}
{% set version = "0.0.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/fastdownload-{{ version }}.tar.gz
  sha256: 20507edb8e89406a1fbd7775e6e2a3d81a4dd633dd506b0e9cf0e1613e831d6a

build:
  skip: true  # [py<36]
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python
    - pip
  run:
    - python
    - fastprogress
    - fastcore >=1.3.26

test:
  imports:
    - fastdownload
  commands:
    - pip check
  requires:
    - pip
    # packaging is unused by fastcore, but `pip check` fails if missing it.
    - packaging

about:
  home: https://github.com/fastai/fastdownload/tree/master/
  summary: A general purpose data downloading library.
  description: |
    If you have datasets or other archives that you want
    to make available to your users, and ensure they always
    have the latest versions and that they are downloaded
    correctly, fastdownload can help.
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  dev_url: https://github.com/fastai/fastdownload
  doc_url: https://fastdownload.fast.ai/

extra:
  recipe-maintainers:
    - giswqs
